/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ProgrammingPC' at '8/3/16 11:49 PM' with Gradle 2.9, IMPORTANT gradle init does not work if
 * the build.gradle file is already defined.
 *
 * @author ProgrammingPC, @date 8/3/16 11:49 PM
 */
public class InsertionSort {
    public boolean someMethod() {
        return true;
    }
}
